#!/usr/bin/env python3
"""
Claude Code が生成したマーケレポート HTML ダッシュボードジェネレーター
入力: sample_data.csv
出力: index.html
"""
import csv
import json
from pathlib import Path

def load_csv(path: str) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def build_dashboard(rows: list[dict]) -> str:
    months   = [r["month"] for r in rows]
    pvs      = [int(r["pv"]) for r in rows]
    sessions = [int(r["sessions"]) for r in rows]
    cvs      = [int(r["cv"]) for r in rows]
    cv_rates = [float(r["cv_rate"]) for r in rows]
    costs    = [int(r["cost"]) for r in rows]
    cpas     = [int(r["cpa"]) for r in rows]

    total_cv   = sum(cvs)
    total_cost = sum(costs)
    avg_cpa    = total_cost // total_cv
    last_month = rows[-1]
    prev_month = rows[-2]
    pv_growth  = round((int(last_month["pv"]) / int(prev_month["pv"]) - 1) * 100, 1)
    cv_growth  = round((int(last_month["cv"]) / int(prev_month["cv"]) - 1) * 100, 1)

    data_json = json.dumps({
        "months": months, "pvs": pvs, "sessions": sessions,
        "cvs": cvs, "cv_rates": cv_rates, "costs": costs, "cpas": cpas
    }, ensure_ascii=False)

    return f"""<!DOCTYPE html>
<html lang=\"ja\">
<head>
<meta charset=\"UTF-8\">
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<title>マーケティングダッシュボード 2025-11〜2026-04</title>
<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js\"></script>
<style>
  :root {{
    --bg: #0f172a; --card: #1e293b; --border: #334155;
    --text: #f1f5f9; --muted: #94a3b8;
    --blue: #3b82f6; --green: #22c55e; --amber: #f59e0b; --rose: #f43f5e;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: \"Helvetica Neue\", Arial, sans-serif; padding: 24px; }}
  h1 {{ font-size: 1.4rem; font-weight: 700; margin-bottom: 4px; }}
  .subtitle {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 24px; }}
  .kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 28px; }}
  .kpi {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 20px; }}
  .kpi .label {{ font-size: 0.78rem; color: var(--muted); margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.05em; }}
  .kpi .value {{ font-size: 1.8rem; font-weight: 700; }}
  .kpi .badge {{ display: inline-block; font-size: 0.72rem; padding: 2px 8px; border-radius: 99px; margin-top: 6px; font-weight: 600; }}
  .badge.up {{ background: rgba(34,197,94,0.15); color: var(--green); }}
  .badge.down {{ background: rgba(244,63,94,0.15); color: var(--rose); }}
  .charts {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
  @media (max-width: 680px) {{ .charts {{ grid-template-columns: 1fr; }} }}
  .chart-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 20px; }}
  .chart-card h2 {{ font-size: 0.9rem; color: var(--muted); margin-bottom: 16px; }}
  .footer {{ margin-top: 28px; text-align: center; font-size: 0.75rem; color: var(--muted); }}
</style>
</head>
<body>
<h1>📊 マーケティングダッシュボード</h1>
<p class=\"subtitle\">2025年11月〜2026年4月 — Claude Code 自動生成レポート</p>
<div class=\"kpi-grid\">
  <div class=\"kpi\"><div class=\"label\">直近月 PV</div><div class=\"value\" style=\"color:var(--blue)\">{int(last_month['pv']):,}</div><span class=\"badge up\">+{pv_growth}% MoM</span></div>
  <div class=\"kpi\"><div class=\"label\">直近月 CV</div><div class=\"value\" style=\"color:var(--green)\">{int(last_month['cv'])}</div><span class=\"badge up\">+{cv_growth}% MoM</span></div>
  <div class=\"kpi\"><div class=\"label\">累計 CV (6ヶ月)</div><div class=\"value\" style=\"color:var(--amber)\">{total_cv}</div><span class=\"badge up\">6ヶ月合計</span></div>
  <div class=\"kpi\"><div class=\"label\">平均 CPA</div><div class=\"value\" style=\"color:var(--rose)\">¥{avg_cpa:,}</div><span class=\"badge up\">6ヶ月平均</span></div>
</div>
<div class=\"charts\">
  <div class=\"chart-card\"><h2>セッション・PV 推移</h2><canvas id=\"trafficChart\" height=\"200\"></canvas></div>
  <div class=\"chart-card\"><h2>CV 数・CV 率 推移</h2><canvas id=\"cvChart\" height=\"200\"></canvas></div>
  <div class=\"chart-card\"><h2>広告費 推移 (円)</h2><canvas id=\"costChart\" height=\"200\"></canvas></div>
  <div class=\"chart-card\"><h2>CPA 推移 (円)</h2><canvas id=\"cpaChart\" height=\"200\"></canvas></div>
</div>
<p class=\"footer\">⚠️ このレポートのデータはデモ用フィクションです。実際の数値ではありません。<br>Generated by Claude Code · {last_month['month']}</p>
<script>
const d = {data_json};
const opt = (y2) => ({{
  responsive: true,
  plugins: {{ legend: {{ labels: {{ color: '#94a3b8', boxWidth: 12 }} }} }},
  scales: {{
    x: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ color: '#1e293b' }} }},
    y: {{ ticks: {{ color: '#94a3b8' }}, grid: {{ color: '#334155' }} }},
    ...(y2 ? {{ y2: {{ type:'linear', position:'right', ticks:{{ color:'#94a3b8' }}, grid:{{ drawOnChartArea:false }} }} }} : {{}})
  }}
}});
new Chart(document.getElementById('trafficChart'), {{ type:'bar', data: {{ labels:d.months, datasets:[{{label:'PV',data:d.pvs,backgroundColor:'rgba(59,130,246,0.7)',borderRadius:4}},{{label:'セッション',data:d.sessions,backgroundColor:'rgba(99,102,241,0.7)',borderRadius:4}}] }}, options:opt(false) }});
new Chart(document.getElementById('cvChart'), {{ type:'bar', data: {{ labels:d.months, datasets:[{{label:'CV数',data:d.cvs,backgroundColor:'rgba(34,197,94,0.7)',borderRadius:4,yAxisID:'y'}},{{label:'CV率(%)',data:d.cv_rates,type:'line',borderColor:'#f59e0b',backgroundColor:'rgba(245,158,11,0.15)',yAxisID:'y2',tension:0.4,fill:true}}] }}, options:opt(true) }});
new Chart(document.getElementById('costChart'), {{ type:'line', data: {{ labels:d.months, datasets:[{{label:'広告費',data:d.costs,borderColor:'#f43f5e',backgroundColor:'rgba(244,63,94,0.1)',tension:0.4,fill:true}}] }}, options:opt(false) }});
new Chart(document.getElementById('cpaChart'), {{ type:'line', data: {{ labels:d.months, datasets:[{{label:'CPA',data:d.cpas,borderColor:'#a78bfa',backgroundColor:'rgba(167,139,250,0.1)',tension:0.4,fill:true}}] }}, options:opt(false) }});
</script>
</body>
</html>"""

if __name__ == "__main__":
    rows = load_csv("sample_data.csv")
    html = build_dashboard(rows)
    Path("index.html").write_text(html, encoding="utf-8")
    print(f"✅ index.html を生成しました ({len(html):,} bytes)")
